const express = require('express')
const router = express.Router()
const admin = require('./modules/admin')
const auth = require('./modules/auth')
const voiceClass = require('./modules/class')
const favorite = require('./modules/favorite')
const like = require('./modules/like')
const user = require('./modules/user')
const home = require('./modules/home')
const { authenticated } = require('../middlewares/auth.js')

router.use('/auth', auth)
router.use('/user', user)
router.use('/admin', authenticated, admin)
router.use('/classes', authenticated, voiceClass)
router.use('/favorites', authenticated, favorite)
router.use('/like', authenticated, like)
router.use('/', authenticated, home)

module.exports = router
